### PR TITLE
10X_Assignment1

### PR DESCRIPTION
**Pull request by HarsH-singHh**

### CODE REVIEW

**Comment by Abduliitr** [comment]
Task is completed, but image width is not appropriate

**Comment by HarsH-singHh** [comment]
> Task is completed, but image width is not appropriate

Sir, there wasn't any instruction for width. W
hat should be the desired width?

**Comment by Abduliitr** [comment]
There is an image of the task in the problem statement (word doc), which shows the image uses 50% width... 

image


Anyway, this is also okay. But if you can do that, then it's better.

**Comment by HarsH-singHh** [comment]
> There is an image of the task in the problem statement (word doc), which shows the image uses 50% width...
> 
> image
> 
> Anyway, this is also okay. But if you can do that, then it's better.

sir I have given width 49%, so I hv to change it? or overflow :hidden will work for parent div of img.

**Comment by Abduliitr** [comment]
It's up to you, whatever you can do to improve it. But as I mentioned, this also is considered as Correct (Task completed).

**Review by ygoyal25 — APPROVED** [review]

**Comment by durgeshkryadav** [comment]
Executed 4 of 4 test cases successfully (code and the output seem correct)...



Screenshot (485)

**Pull request merged**
